sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=davidemoro/pytest-play
before_install:
  - travis_wait 25 docker build -t "$IMAGE_NAME" .
script:
  - docker run -i --rm -v $(pwd)/tests:/src $IMAGE_NAME
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
