sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=davidemoro/pytest-play
before_install:
  - docker build -t "$IMAGE_NAME" .
  - docker ps -a
script:
  - docker run -d --rm -v $(pwd)/tests:/src $IMAGE_NAME
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
