sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=davidemoro/pytest-play
script:
- travis_wait docker pull python:3.6.8-alpine3.8
- travis_wait docker pull "$IMAGE_NAME:latest"
- travis_wait 25 docker build --cache-from "$IMAGE_NAME:latest" -t "$IMAGE_NAME" .
- docker run -i --rm -v $(pwd)/tests:/src $IMAGE_NAME
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
