#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag "$TRAVIS_COMMIT" "$IMAGE_NAME"
docker push "$IMAGE_NAME":latest
docker push "$IMAGE_NAME":"$TRAVIS_COMMIT"
