#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag "$IMAGE_NAME" "$IMAGE_NAME:$TRAVIS_COMMIT"
docker tag "$IMAGE_NAME" "$IMAGE_NAME:latest"
docker push "$IMAGE_NAME":"$TRAVIS_COMMIT"
docker push "$IMAGE_NAME":latest
